---
# Variables specific to BGP nodes

# etcd cluster configuration
etcd_cluster_members: "{% for host in groups['etcd_cluster'] %}{{ host }}=http://{{ hostvars[host]['node_ip'] }}:2380{% if not loop.last %},{% endif %}{% endfor %}"
etcd_endpoints: "{% for host in groups['etcd_cluster'] %}{{ hostvars[host]['node_ip'] }}:2379{% if not loop.last %},{% endif %}{% endfor %}"

# TINC peer list (all nodes except self)
tinc_peers: "{{ groups['tinc_mesh'] | difference([inventory_hostname]) }}"

# BGP peer list (all nodes except self)
bgp_peers: "{% set peers = [] %}{% for host in groups['bird_routers'] if host != inventory_hostname %}{% set _ = peers.append({'name': host, 'ip': hostvars[host]['node_ip']}) %}{% endfor %}{{ peers }}"
