---
- name: Install etcd dependencies
  apt:
    name:
      - curl
      - tar
    state: present
    update_cache: yes

- name: Create etcd user
  user:
    name: etcd
    system: yes
    create_home: no
    shell: /usr/sbin/nologin

- name: Create etcd directories
  file:
    path: "{{ item }}"
    state: directory
    owner: etcd
    group: etcd
    mode: '0755'
  loop:
    - /etc/etcd
    - /var/lib/etcd

- name: Check if etcd is installed
  stat:
    path: /usr/local/bin/etcd
  register: etcd_binary

- name: Download and extract etcd
  when: not etcd_binary.stat.exists
  block:
    - name: Download etcd tarball
      get_url:
        url: "https://github.com/etcd-io/etcd/releases/download/v{{ etcd_version }}/etcd-v{{ etcd_version }}-linux-amd64.tar.gz"
        dest: "/tmp/etcd-v{{ etcd_version }}-linux-amd64.tar.gz"
        mode: '0644'

    - name: Extract etcd
      unarchive:
        src: "/tmp/etcd-v{{ etcd_version }}-linux-amd64.tar.gz"
        dest: /tmp
        remote_src: yes

    - name: Install etcd binaries
      copy:
        src: "/tmp/etcd-v{{ etcd_version }}-linux-amd64/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        mode: '0755'
        owner: root
        group: root
        remote_src: yes
      loop:
        - etcd
        - etcdctl

- name: Create etcd configuration
  template:
    src: etcd.conf.j2
    dest: /etc/etcd/etcd.conf
    owner: etcd
    group: etcd
    mode: '0644'
  notify: restart etcd

- name: Create etcd systemd service
  template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - reload systemd
    - restart etcd

- name: Enable and start etcd service
  systemd:
    name: etcd
    enabled: yes
    state: started
    daemon_reload: yes
