---
# Global variables for BGP network

# TINC VPN settings
tinc_netname: "bgpmesh"
tinc_port: 655
tinc_subnet_mask: 24
tinc_mtu: 1400

# BGP settings
bgp_as: 65000
bgp_bfd_enabled: false

# etcd cluster settings
etcd_version: "3.5.14"
etcd_cluster_token: "bgp-mesh-cluster"

# Monitoring
prometheus_port: 9090
grafana_port: 3000

# Node-specific settings (will be overridden by host_vars)
node_name: "{{ inventory_hostname }}"
