---
- name: Install BIRD BGP daemon
  apt:
    name:
      - bird2
    state: present
    update_cache: yes

- name: Create BIRD configuration directory
  file:
    path: /etc/bird
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Deploy BIRD main configuration
  template:
    src: bird.conf.j2
    dest: /etc/bird/bird.conf
    owner: root
    group: root
    mode: '0644'
    validate: 'bird -p -c %s'
  notify: restart bird

- name: Create BIRD protocols configuration
  template:
    src: protocols.conf.j2
    dest: /etc/bird/protocols.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart bird

- name: Create BIRD systemd override directory
  file:
    path: /etc/systemd/system/bird.service.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Deploy BIRD systemd override
  template:
    src: bird-override.conf.j2
    dest: /etc/systemd/system/bird.service.d/override.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - reload systemd
    - restart bird

- name: Enable and start BIRD service
  systemd:
    name: bird
    enabled: yes
    state: started
    daemon_reload: yes
