name: CI

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main ]

jobs:
  validate:
    name: Validate Configuration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate environment variables
        run: ./tests/validation/test_env_vars.sh

      - name: Install YAML linter
        run: sudo apt-get update && sudo apt-get install -y yamllint

      - name: Lint YAML files
        run: |
          yamllint docker-compose.yml
          find configs/ -name "*.yml" -exec yamllint {} \;

  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs: validate

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build BIRD image
        run: docker build ./docker/bird -t bgp-bird:ci

      - name: Build TINC image
        run: docker build ./docker/tinc -t bgp-tinc:ci

      - name: Build Monitoring image
        run: docker build ./docker/monitoring -t bgp-monitoring:ci

  test-go:
    name: Test Go Daemon
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Download dependencies
        working-directory: ./daemon-go
        run: make deps

      - name: Run go vet
        working-directory: ./daemon-go
        run: make vet

      - name: Run go fmt check
        working-directory: ./daemon-go
        run: |
          if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
            echo "Code is not formatted:"
            gofmt -s -l .
            exit 1
          fi

      - name: Run unit tests
        working-directory: ./daemon-go
        run: make test-unit

      - name: Run race detector
        working-directory: ./daemon-go
        run: make test-race

      - name: Run tests with coverage
        working-directory: ./daemon-go
        run: make test-coverage

      - name: Check coverage threshold
        working-directory: ./daemon-go
        run: |
          COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print $3}' | sed 's/%//')
          echo "Current coverage: ${COVERAGE}%"
          if (( $(echo "$COVERAGE < 70" | bc -l) )); then
            echo "⚠️  Coverage ${COVERAGE}% is below threshold 70%"
            echo "This is expected in Sprint 2 Phase 1 as pkg/tinc and pkg/discovery tests are pending"
            echo "Target for Phase 2: >70%"
          else
            echo "✅ Coverage ${COVERAGE}% meets or exceeds threshold 70%"
          fi

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        continue-on-error: true
        with:
          file: ./daemon-go/coverage.out
          flags: unittests
          fail_ci_if_error: false

      - name: Build daemon
        working-directory: ./daemon-go
        run: make build

  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [build, test-go]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy environment file
        run: cp .env.example .env

      - name: Deploy local environment
        run: make deploy-local

      - name: Wait for convergence
        run: sleep 90

      - name: Run integration tests
        run: make test-integration

      - name: Show logs on failure
        if: failure()
        run: |
          echo "=== Docker PS ==="
          docker ps -a
          echo "=== BIRD1 Logs ==="
          docker logs bird1 || true
          echo "=== TINC1 Logs ==="
          docker logs tinc1 || true
          echo "=== ETCD1 Logs ==="
          docker logs etcd1 || true

      - name: Cleanup
        if: always()
        run: make clean

  summary:
    name: CI Summary
    runs-on: ubuntu-latest
    needs: [validate, build, test-go, integration]
    if: always()

    steps:
      - name: Check job results
        run: |
          echo "Validate: ${{ needs.validate.result }}"
          echo "Build: ${{ needs.build.result }}"
          echo "Test Go: ${{ needs.test-go.result }}"
          echo "Integration: ${{ needs.integration.result }}"

          if [ "${{ needs.validate.result }}" != "success" ] || \
             [ "${{ needs.build.result }}" != "success" ] || \
             [ "${{ needs.test-go.result }}" != "success" ] || \
             [ "${{ needs.integration.result }}" != "success" ]; then
            echo "❌ CI pipeline failed"
            exit 1
          fi

          echo "✅ All CI checks passed"
